# Rock Classification

# import standard library

In [1]:
import os
import cv2
import shutil
import numpy as np
import pandas as pd
from tqdm import tqdm
import tensorflow as tf
from keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# see the current directory

In [2]:
pwd

### pwd stands for "print working directory". 
### It is a command used in a command-line interface (CLI) or terminal to display the current working directory.
### In other words, it shows you the directory you are currently in.

'C:\\Users\\SATHYANARAYANA M'

# printing count of images

In [3]:
# Loop through all the directories and files in the folder
# Print the number of files in the current directory

for i in os.listdir("C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset"): ### os.listdir method returns a list of all the files 
    print(len(os.listdir("C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\" + str(i))))

86
369
101
338
387
477
325


In [4]:
image_loc = "C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset"

In [5]:
class_loc = []                                   # Create an empty list called class_loc
for i in os.listdir(image_loc):                  # Loop through all the directories and files in the image_loc directory
    class_loc.append(os.path.join(image_loc,i))  # For each directory, append its full path to the class_loc list using the os.path.join() method

In [6]:
class_loc

['C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Coal',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Granite',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Limestone',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Marble',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Quartzite',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Sandstone']

In [7]:
image_path = []
for i in class_loc:
    for j in os.listdir(i):
        image_path.append(os.path.join(i,j))

In [8]:
image_path

['C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\1.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\10.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\11.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\12.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\13.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\14.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\148248735-grey-rock-pile-isolated-on-white-background.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\15.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\16.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\17.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock dataset\\Basalt\\18.jpg',
 'C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\Rock data

# creating a Data Frame

In [9]:
img_df = pd.DataFrame(image_path, columns = ['path'])

In [10]:
img_df

path
0     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
1     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
2     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
3     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
4     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
...                                                 ...
2078  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
2079  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
2080  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
2081  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...
2082  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...

[2083 rows x 1 columns]

In [11]:
img_df['label'] = None

In [12]:
img_df['path'][2].split('\\')[6] #### checking the spliting

'Basalt'

In [13]:
for i,j in enumerate(img_df['path']):
    img_df['label'][i] = img_df['path'][i].split('\\')[6]                                                  

In [14]:
img_df

path      label
0     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
1     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
2     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
3     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
4     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
...                                                 ...        ...
2078  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2079  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2080  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2081  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2082  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone

[2083 rows x 2 columns]

# spliting train and test

In [16]:
train,test = train_test_split(img_df, test_size = 0.2, stratify = img_df['label'])   ### stratify is used when dataset is imbalanced
train.to_csv('C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\train.csv', index = False)
test.to_csv('C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\test.csv', index = False)

In [18]:
for file_location,label in tqdm(zip(train['path'],train['label'])):
    file_name = file_location.split('\\')[-1]
    shutil.copy2(file_location, f"C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\train\\{label}\\{file_name}")

1666it [00:16, 100.22it/s]


In [19]:
for file_location,label in tqdm(zip(test['path'],test['label'])):
    file_name = file_location.split('\\')[-1]
    shutil.copy2(file_location, f"C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\test\\{label}\\{file_name}")

417it [00:04, 98.70it/s] 


In [20]:
img_df

path      label
0     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
1     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
2     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
3     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
4     C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...     Basalt
...                                                 ...        ...
2078  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2079  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2080  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2081  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone
2082  C:\Users\SATHYANARAYANA M\OneDrive\Desktop\Roc...  Sandstone

[2083 rows x 2 columns]

In [67]:
train_images = image_resize(256,256,train)
test_images = image_resize(256,256,test)

100%|████████████████████████████████████████████████████████████████████████████████| 417/417 [00:08<00:00, 49.41it/s]


In [24]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                  shear_range = 0.1,
                                  zoom_range = 0.1,
                                  horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [25]:
train_datagen

In [26]:
# Training Set
train_set = train_datagen.flow_from_directory("C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\train",
                                             target_size = (256,256),
                                             batch_size = 4,
                                             class_mode = 'categorical')

Found 2069 images belonging to 7 classes.


In [28]:
# Testing Set
test_set = test_datagen.flow_from_directory("C:\\Users\\SATHYANARAYANA M\\OneDrive\\Desktop\\test",
                                           target_size = (256,256),
                                           batch_size = 4,
                                           class_mode = 'categorical',
                                           shuffle = False)

Found 1226 images belonging to 7 classes.


In [33]:
# Define the early stopping callback
early_stop = EarlyStopping(monitor='val_loss', patience=4)

# Layers of Cnn

In [34]:
classifier = tf.keras.models.Sequential(
    [
        tf.keras.layers.Conv2D(16,3,activation='relu',input_shape=(256,256,3)), 
        tf.keras.layers.MaxPool2D((2,2)),
        tf.keras.layers.Conv2D(8,2,activation='relu'),
        tf.keras.layers.MaxPool2D((2,2)),
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(128,activation = 'relu'),
        tf.keras.layers.Dense(7,activation = 'softmax')
    ]
)

# compile and summary

In [35]:
classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])
classifier.summary()

### categorical_crossentropy is a loss function that is commonly used in multi-class classification problems.

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 254, 254, 16)      448       
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 127, 127, 16)     0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 126, 126, 8)       520       
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 63, 63, 8)        0         
 2D)                                                             
                                                                 
 flatten_1 (Flatten)         (None, 31752)             0         
                                                                 
 dense_2 (Dense)             (None, 128)              

# Runing epoch

In [ ]:
### Runnig epoch 20 times i get an beat accuracy

In [37]:
history = classifier.fit_generator(train_set,
                         steps_per_epoch = 500,
                         epochs = 20,
                        validation_data = test_set)

C:\Users\SATHYANARAYANA M\AppData\Local\Temp\ipykernel_9444\3499804916.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history = classifier.fit_generator(train_set,


Epoch 1/20
500/500 [==============================] - 102s 205ms/step - loss: 0.9690 - accuracy: 0.6660 - val_loss: 0.7182 - val_accuracy: 0.7545
Epoch 2/20
500/500 [==============================] - 103s 205ms/step - loss: 0.8904 - accuracy: 0.6925 - val_loss: 0.6666 - val_accuracy: 0.7732
Epoch 3/20
500/500 [==============================] - 104s 209ms/step - loss: 0.8286 - accuracy: 0.7076 - val_loss: 0.6645 - val_accuracy: 0.7602
Epoch 4/20
500/500 [==============================] - 104s 209ms/step - loss: 0.7583 - accuracy: 0.7336 - val_loss: 0.5015 - val_accuracy: 0.8189
Epoch 5/20
500/500 [==============================] - 104s 207ms/step - loss: 0.7480 - accuracy: 0.7386 - val_loss: 0.5633 - val_accuracy: 0.8002
Epoch 6/20
500/500 [==============================] - 104s 208ms/step - loss: 0.6794 - accuracy: 0.7546 - val_loss: 0.4602 - val_accuracy: 0.8385
Epoch 7/20
500/500 [==============================] - 104s 208ms/step - loss: 0.6070 - accuracy: 0.7902 - val_loss: 0.4950 -

In [59]:
import matplotlib.pyplot as plt


In [62]:
!pip install utils

In [49]:
classifier.predict(test_set)

307/307 [==============================] - 13s 41ms/step


array([[9.9993300e-01, 3.9039937e-06, 4.5120882e-10, ..., 9.2099887e-12,
        1.4191852e-10, 1.6567735e-13],
       [9.9999762e-01, 2.3872005e-06, 7.2057131e-11, ..., 5.4431711e-12,
        4.7732252e-11, 1.5050100e-15],
       [9.9999976e-01, 6.8444589e-10, 6.9710091e-09, ..., 8.4637325e-10,
        1.7282093e-07, 1.1859675e-07],
       ...,
       [7.6449087e-06, 1.8036812e-06, 5.6466790e-05, ..., 7.8415480e-03,
        1.9892599e-04, 9.9185514e-01],
       [2.1175893e-07, 3.0615786e-07, 5.8632628e-05, ..., 1.7939426e-06,
        4.8399885e-04, 9.9934560e-01],
       [3.5992276e-31, 3.6144254e-34, 1.5416303e-26, ..., 1.3465563e-22,
        1.3395432e-21, 1.0000000e+00]], dtype=float32)

In [50]:
y_pred = classifier.predict(test_set)

307/307 [==============================] - 13s 43ms/step


In [51]:
np.argmax(y_pred, axis=-1)

array([0, 0, 0, ..., 6, 6, 6], dtype=int64)

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le = LabelEncoder()
le.fit_transform(test['label'])

array([4, 4, 3, 1, 5, 5, 6, 4, 5, 2, 4, 4, 5, 5, 6, 5, 3, 1, 1, 1, 6, 5,
       4, 6, 3, 4, 6, 4, 5, 6, 4, 1, 5, 5, 0, 5, 4, 4, 3, 2, 6, 4, 3, 4,
       4, 1, 3, 4, 6, 5, 5, 1, 5, 3, 5, 4, 0, 1, 1, 4, 3, 6, 1, 1, 2, 4,
       1, 4, 3, 1, 1, 5, 4, 5, 6, 1, 2, 1, 5, 4, 1, 6, 3, 5, 6, 6, 4, 5,
       1, 1, 1, 6, 4, 1, 2, 4, 4, 5, 5, 4, 6, 1, 5, 3, 5, 6, 3, 6, 4, 4,
       1, 0, 5, 4, 4, 6, 4, 3, 1, 5, 3, 5, 5, 2, 3, 3, 1, 6, 5, 5, 4, 3,
       3, 5, 4, 6, 3, 1, 6, 5, 1, 1, 6, 3, 6, 1, 4, 4, 3, 4, 1, 6, 5, 6,
       1, 3, 3, 1, 5, 0, 4, 4, 6, 1, 4, 3, 6, 5, 4, 1, 3, 5, 5, 2, 3, 1,
       6, 3, 5, 2, 3, 1, 4, 5, 6, 5, 5, 1, 3, 5, 4, 5, 5, 6, 3, 5, 1, 1,
       6, 3, 3, 6, 4, 3, 1, 1, 6, 3, 4, 5, 0, 0, 5, 5, 2, 1, 6, 3, 5, 3,
       6, 6, 2, 5, 6, 3, 4, 3, 4, 5, 4, 3, 4, 1, 6, 6, 5, 6, 3, 1, 6, 1,
       1, 1, 5, 4, 0, 5, 1, 4, 3, 5, 4, 4, 6, 1, 5, 0, 5, 5, 1, 3, 6, 3,
       0, 6, 1, 3, 5, 5, 3, 2, 3, 4, 6, 5, 0, 3, 6, 2, 5, 2, 1, 5, 6, 1,
       4, 5, 5, 5, 3, 1, 5, 5, 6, 3, 5, 6, 1, 5, 4,